<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Test packages -->
    <PackageVersion Include="coverlet.collector" Version="6.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.SDK" Version="17.14.1" />
    <PackageVersion Include="MSTest.TestAdapter" Version="3.11.0" />
    <PackageVersion Include="MSTest.TestFramework" Version="3.11.0" />
    <PackageVersion Include="Shouldly" Version="4.2.1" />
    <!-- Core packages -->
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.8.250916003" />
    <!-- WinForm packages -->
    <PackageVersion Include="7ZipCLI" Version="9.20.0" />
    <PackageVersion Include="Equin.ApplicationFramework.BindingListView" Version="1.4.5222.35545" />
  </ItemGroup>
</Project>
