<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWinUI>true</UseWinUI>
    <AssemblyName>HostsFileEditor</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platform Condition="'$(Platform)' == ''">x64</Platform>
    <Platforms>x64;arm64</Platforms>
    <EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>
    <UseWindowsForms>false</UseWindowsForms>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-x64</RuntimeIdentifier>
    <WindowsAppSDKSelfContained>false</WindowsAppSDKSelfContained>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
    <PublishAot>true</PublishAot>
    <NoWarn>$(NoWarn);IDE0079;IDE0060;CA1822;IL2081</NoWarn>
    <ApplicationIcon>Assets\HostsFileEditor.ico</ApplicationIcon>
    <PackagingFlavor>modern</PackagingFlavor>
    <OutputPackagingDir>$(MSBuildProjectDirectory)\..\artifacts\modern\</OutputPackagingDir>
    <CreatePublishZip>true</CreatePublishZip>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="7ZipCLI" GeneratePathProperty="true" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.WindowsAppSDK" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HostsFileEditor.Core\HostsFileEditor.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="app.manifest" />
    <Content Include="AppxManifest.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="HostsFileEditor.ico" />
  </ItemGroup>
</Project>
